[build]
  publish = "public"
  command = "gatsby-parallel-runner"
  functions = './functions-build/'

[[redirects]]
  from = "/functions/addToNewsletterList"
  to = "/.netlify/functions/addToNewsletterList"
  status = 200
  query = {email = ":email"} # apply this rule for /?path=example
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
