[build]
  command = "gatsby-parallel-runner"
  functions = "lambda"
  publish = "public"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
