backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: event
    identifier_field: title
    label: Event
    folder: src/pages/events
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: event-post
      - label: Event Name
        name: title
        widget: text
      - label: Content
        name: content
        widget: list
        types:
          - label: Images
            name: images
            widget: object
            fields:
              - label: Image
                name: image
                required: false
                widget: image
              - label: Caption
                name: caption
                required: false
                widget: markdown
          - label: Text
            name: text
            widget: object
            fields:
              - label: Body
                name: body
                required: false
                widget: markdown
                buttons:
                  [
                    "bold",
                    "italic",
                    "link",
                    "heading-one",
                    "heading-two",
                    "bulleted-list",
                  ]
      - label: Event Location
        name: location
        widget: text
      - label: Event Date
        name: date
        widget: datetime
  - name: "podcast"
    identifier_field: name
    label: "Podcast"
    folder: "src/pages/podcast"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "podcast-page",
        }
      - { label: "Podcast Name", name: "title", widget: "string" }
      - {
          label: "Body and Podcast URL",
          name: "body",
          widget: "markdown",
          buttons:
            ["bold", "italic", "heading-one", "heading-two", "bulleted-list"],
        }
      - { label: "Podcast Date", name: "date", widget: "datetime" }
  - name: "product"
    label: "Products"
    folder: "src/pages/shop"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Template Key"
        name: "templateKey"
        widget: "hidden"
        default: "product-page"
      - label: "Product Name"
        name: "title"
        widget: "string"
      - label: Upload PDF
        name: PDF
        required: false
        widget: file
      - label: Content
        name: content
        widget: list
        types:
          - label: Images
            name: images
            widget: object
            fields:
              - label: Image
                name: image
                required: false
                widget: image
              - label: Caption
                name: caption
                required: false
                widget: markdown
          - label: Text
            name: text
            widget: object
            fields:
              - label: Body
                name: body
                required: false
                widget: markdown
                buttons:
                  [
                    "bold",
                    "italic",
                    "link",
                    "heading-one",
                    "heading-two",
                    "bulleted-list",
                  ]
      - label: Author
        name: author
        widget: string
      - label: Date Added
        name: date
        widget: datetime
  - name: "focus"
    label: "Focus"
    folder: "src/pages/focus"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Template Key"
        name: "templateKey"
        widget: "hidden"
        default: "focus-page"
      - label: Article Title
        name: title
        widget: string
      - label: Upload PDF
        name: "PDF"
        widget: "file"
      - label: Content
        name: content
        widget: list
        types:
          - label: Images
            name: images
            widget: object
            fields:
              - label: Image
                name: image
                required: false
                widget: image
              - label: Caption
                name: caption
                required: false
                widget: markdown
          - label: Text
            name: text
            widget: object
            fields:
              - label: Body
                name: body
                required: false
                widget: markdown
                buttons:
                  [
                    "bold",
                    "italic",
                    "link",
                    "heading-one",
                    "heading-two",
                    "bulleted-list",
                  ]
      - label: "Author"
        name: "author"
        widget: "string"
      - label: Date
        name: date
        widget: datetime
  - name: "about"
    label: "About"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { Label: "Left Column", name: "leftColumn", widget: "markdown" }
          - { Label: "Right Column", name: "body", widget: "markdown" }
          - {
              label: List of Contributors / contact information,
              name: blurbs,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: SubTitle, name: subtitle, widget: string },
                ],
            }
          - { Label: "Additional Info", name: "other", widget: "markdown" }
