backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Events"
    folder: "src/pages/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Warehouse Number", name: "warehouseID", widget: "string", hint: "For example WAREHOUSE #3.5"}
      - {label: "Event Name", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", buttons: ["bold", "italic", "link", "heading-one", "heading-two", "bulleted-list"]}
      - {label: "Event Location", name: "location", widget: "string"}
      - {label: "Event Date", name: "date", widget: "datetime"}

  - name: "podcast"
    identifier_field: name
    label: "Podcast"
    folder: "src/pages/podcast"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "podcast-page"}
      - {label: "Warehouse Number", name: "warehouseID", widget: "string", hint: "For example WAREHOUSE #3.5"}
      - {label: "Podcast Name", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", buttons: ["bold", "italic", "link", "heading-one", "heading-two", "bulleted-list"]}
      - {label: "Podcast ID (9 Numbers)", name: "podcastURL", widget: "number", valueType: "int" }
      - {label: "Podcast Date", name: "date", widget: "datetime"}

  - name: "product"
    label: "Products"
    folder: "src/pages/shop"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
      - {label: "Warehouse Number", name: "warehouseID", widget: "string", hint: "For example WAREHOUSE #3.5"}
      - {label: "Product Name", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", buttons: ["bold", "italic", "link", "heading-one", "heading-two", "bulleted-list"]}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Date Added", name: "date", widget: "datetime"}

  - name: "focus"
    label: "Focus"
    folder: "src/pages/focus"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "focus-page"}
      - {label: "Warehouse Number", name: "warehouseID", widget: "string", hint: "For example WAREHOUSE #3.5"}
      - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
      - {label: "Product Name", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", buttons: ["bold", "italic", "link", "heading-one", "heading-two", "bulleted-list"]}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Date Added", name: "date", widget: "datetime"}


  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object,
              fields: [
                {label: Title, name: title, widget: string},
                {label: Description, name: description, widget: text}
              ]
            }
          - {label: Description, name: description, widget: string}

          - {label: Intro, name: intro, widget: object,
              fields: [
                {label: Heading, name: heading, widget: string},
                {label: Description, name: description, widget: text},
                {label: Blurbs, name: blurbs, widget: list,
                  fields: [
                    {label: Image, name: image, widget: image},
                    {label: Text, name: text, widget: text}
                  ]
                }
              ]
            }
          - {label: Main, name: main, widget: object,
              fields: [
                {label: Heading, name: heading, widget: string},
                {label: Description, name: description, widget: text},
                {label: Image1, name: image1, widget: object,
                  fields: [
                    {label: Image, name: image, widget: image},
                    {label: Alt, name: alt, widget: string}
                  ]},
                {label: Image2, name: image2, widget: object,
                  fields: [
                    {label: Image, name: image, widget: image},
                    {label: Alt, name: alt, widget: string}
                  ]
                },
                {label: Image3, name: image3, widget: object,
                  fields: [
                    {label: Image, name: image, widget: image},
                    {label: Alt, name: alt, widget: string}
                  ]
                }
              ]
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
