backend:
    name: git-gateway
    branch: master

media_folder: public/img
public_folder: img

collections:
    - name: event
      identifier_field: title
      label: Event
      folder: content/events
      create: true
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
      fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: event-post
          - label: Event Name
            name: title
            widget: text
          - label: Content
            name: content
            widget: list
            types:
                - label: Images
                  name: images
                  widget: object
                  fields:
                      - label: Image
                        name: image
                        required: false
                        widget: image
                      - label: Caption
                        name: caption
                        required: false
                        widget: markdown
                - label: Text
                  name: text
                  widget: object
                  fields:
                      - label: Body
                        name: body
                        required: false
                        widget: markdown
                        buttons:
                            [
                                'bold',
                                'italic',
                                'link',
                                'heading-one',
                                'heading-two',
                                'bulleted-list',
                            ]
          - label: Event Location
            name: location
            widget: text
          - label: Event Date
            name: date
            widget: date
            default: ''
            format: 'YYYY-MM-DD'
    - name: 'podcast'
      identifier_field: name
      label: 'Podcast'
      folder: 'content/podcast'
      create: true
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
      fields:
          - {
                label: 'Template Key',
                name: 'templateKey',
                widget: 'hidden',
                default: 'podcast-page',
            }
          - { label: 'Podcast Name', name: 'title', widget: 'string' }
          - {
                label: 'Body and Podcast URL',
                name: 'body',
                widget: 'markdown',
                buttons: ['bold', 'italic', 'heading-one', 'heading-two', 'bulleted-list'],
            }
          - { label: 'Podcast Date', name: 'date', widget: date, default: '', format: 'YYYY-MM-DD' }
    - name: 'product'
      label: 'Products'
      folder: 'content/shop'
      create: true
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
      fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: product-page
          - label: Product Name
            name: title
            widget: string
          - label: Price EUR
            name: price
            widget: string
            required: false
          - label: BTW
            name: btw
            widget: select
            options: ['9', '21']
            default: '21'
          - label: Upload PDF
            name: PDF
            required: false
            widget: file
          - label: Content
            name: content
            widget: list
            types:
                - label: Images
                  name: images
                  widget: object
                  fields:
                      - label: Image
                        name: image
                        required: false
                        widget: image
                      - label: Caption
                        name: caption
                        required: false
                        widget: markdown
                - label: Text
                  name: text
                  widget: object
                  fields:
                      - label: Body
                        name: body
                        required: false
                        widget: markdown
                        buttons:
                            [
                                'bold',
                                'italic',
                                'link',
                                'heading-one',
                                'heading-two',
                                'bulleted-list',
                            ]
                - label: Cart Button
                  name: cart-button
                  widget: object
                  fields:
                      - label: Text
                        name: text
                        widget: string
                        default: Add to cart
          - label: Author
            name: author
            widget: string
          - label: Date Added
            name: date
            widget: date
            default: ''
            format: 'YYYY-MM-DD'
    - name: focus
      label: Focus
      folder: 'content/focus'
      create: true
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
      fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: focus-page
          - label: Article Title
            name: title
            widget: string
          - label: Upload PDF
            name: PDF
            widget: file
          - label: Content
            name: content
            widget: list
            types:
                - label: Images
                  name: images
                  widget: object
                  fields:
                      - label: Image
                        name: image
                        required: false
                        widget: image
                      - label: Caption
                        name: caption
                        required: false
                        widget: markdown
                - label: Text
                  name: text
                  widget: object
                  fields:
                      - label: Body
                        name: body
                        required: false
                        widget: markdown
                        buttons:
                            [
                                'bold',
                                'italic',
                                'link',
                                'heading-one',
                                'heading-two',
                                'bulleted-list',
                            ]
          - label: 'Author'
            name: 'author'
            widget: 'string'
          - label: Date
            name: date
            widget: date
            default: ''
            format: 'YYYY-MM-DD'
    - name: 'about'
      label: 'About'
      files:
          - file: 'content/about/index.md'
            label: About
            name: about
            fields:
                - label: Template Key
                  name: templateKey
                  widget: hidden
                  default: about-page
                - label: Title
                  name: title
                  widget: string
                - label: Left Column
                  name: leftColumn
                  widget: markdown
                - label: Right Column
                  name: rightColumn
                  required: false
                  widget: markdown
                  buttons: ['bold', 'italic', 'link', 'heading-one', 'heading-two', 'bulleted-list']
                - label: Images
                  name: images
                  widget: list
                  fields:
                      - label: Image
                        name: image
                        required: false
                        widget: image
                      - label: Caption
                        name: caption
                        required: false
                        widget: markdown
                - label: Additional Info
                  name: other
                  widget: markdown
    - name: pages
      label: Pages
      folder: 'content/pages'
      create: true
      slug: '{{slug}}'
      fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: pages-page
          - label: Title
            name: title
            widget: string
          - label: Text
            name: text
            required: false
            widget: markdown
            buttons: ['bold', 'italic', 'link', 'heading-one', 'heading-two', 'bulleted-list']
